### ISSUE TITLE
Battery warning (not battery low) doesn't state which zone

### ISSUE THREAD

**Issue by RogerSelwyn** [manzanotti/geniushub-client#31]
The battery warning e.g. 'The battery for the Genius Valve is low' doesn't provide zone information, and therefore isn't localisable to an individual device. I think this this because it is missing {zone_name} from the error message.

**Comment by zxdavb** [comment]
Hello,

Thank you for your submission. I wrote this particular integration and I should be able to help.

However could I ask if you could provide more information such as a screenshot or or a log file?

Also what is the corresponding error message in the the vendors webUI?

Finally: are you able to to use the vendors RESTful api to to see the corresponding error message?

Thanks.

**Comment by RogerSelwyn** [comment]
Hi David,

Thanks for getting back to me. I'll post the message when I next get it in my home assistant logs, but it is as I have shown in my initial post. I'll then try and identify what I can do via Restapi. That said I see the below in your code, which I think means you are generating the message, and that zone name is not include in the battery warning. I've not looked at the v3 api much, I've mostly worked with v1 api, so not sure what errors specifically the api shows (to be honest i wrote code for SmartThings that worked in out from scanning all the devices).

    "node:low_battery": "The battery for the {device_type} in {zone_name} is dead and needs to be replaced",  # correct
    "node:warn_battery": "The battery for the {device_type} is low",

Cheers
Roger

**Comment by zxdavb** [comment]
I will have a look at this, but it's worth saying that  although it uses the v3 API to get the data, (if it can) the code always presents that data as the v1 API would do.

That is if the v1 API doesn't provide the zone name, then neither does this library (even though it could do so).

The primary reason for this is that the v1 API is documented, and the v3 API is not.

**Comment by RogerSelwyn** [comment]
I'm not sure where the issues are listed in documentation. I just had a look at the v1 docs and they just give a singular example. At the moment the battery low warning is intermittent and I only spot it because it appears in my HA logs, I've never seen it before through my Smartthings integration, but then I never called the Issues node.
