### ISSUE TITLE
Unable to login with V3

### ISSUE THREAD

**Issue by GeoffAtHome** [manzanotti/geniushub-client#45]
All was working fine with HA until the latest update. I can no longer connect to my Genius Hub.

I am testing standalone with ghclient.py with correct local IP address, username and password. The follow error is produced:
```
Exception has occurred: ClientConnectorError
Cannot connect to host http:80 ssl:default [getaddrinfo failed]
  File "D:\demos\geniushub-client\geniushubclient\session.py", line 45, in request
    async with http_method(
  File "D:\demos\geniushub-client\geniushubclient\__init__.py", line 248, in update
    zones, data_manager, auth = await asyncio.gather(
  File "D:\demos\geniushub-client\ghclient.py", line 191, in main
    await hub.update()  # initialise: enumerate all zones, devices & issues
  File "D:\demos\geniushub-client\ghclient.py", line 262, in <module>
    LOOP.run_until_complete(main(LOOP))
```

Doing the same (local IP address, username and password) from https://pypi.org/project/geniushub/  => https://github.com/GeoffAtHome/geniushub connects fine.

I am wondering if anyone else is seeing this issue or is it my system and setup?

Will investigate more later... just reaching out incase someone else has see the same issue.

**Comment by manzanotti** [comment]
I'll give it a try later this afternoon. What hub firmware version are you running?

**Comment by GeoffAtHome** [comment]
Hub version 5.3.8 (I believe - app isn't currently showing me what version I am running). I have tried to upgrade to the latest (5.4.0) but it never seems to complete - I have an open bug with Genius hub about this. This could be related but I am unsure. Maybe the upgrade is leaving the hub in an odd state. I'll try rebooting the hub to see if this improves things. I know the code hasn't not changed so am really in the dark as to why my setup is in such an odd state.

**Comment by manzanotti** [comment]
Just to confirm, I can connect to the V3 API.

I'm on 5.4, they updated it for me, as my Hub-B was failing to update itself.

**Comment by GeoffAtHome** [comment]
Many thanks for the confirmation. I push the Genius team to update my hub and try again. I am hoping this is the cause of the problem.

**Comment by GeoffAtHome** [comment]
Hub upgraded to 5.4.0 and problem has now gone. Strange but I am happy.
