### ISSUE TITLE
Switches

### ISSUE THREAD

**Issue by GeoffAtHome** [manzanotti/geniushub-client#51]
I am trying to write an automation in HA for a switch.  

The switch exists in its own zone in Genius Hub.

In HA the switch appears the following two entities:
- binary_sensor.smart_plug_4
- switch.zone_name

**binary_sensor.smart_plug_4** service data
_assigned_zone:_ zone_name socket
_last_comms:_ '2021-01-21T15:30:59+00:00'
_state:_ {}
_friendly_name:_ Smart Plug 4

**switch.zone_name** service data
_entity_id:_ switch.zone_name

I have tried turning the switch off and on calling the service _**switch.turn_off**_ and **_switch.turn_on_**
I have tried using the services **_geniushub.set_zone_mode_** and **_geniushub.set_zone_override_**

The HA documentation for the GH states:
_Individual smart plugs are not yet exposed as switches - you can create one zone per smart plug as a work-around._

Am I missing something or a setup/user error on my part, but how do I toggle the switch on and off from HA?

Happy to extend the code to support this if needed but just wanted to check here first incase it is user error on my part or not.

If the code needs to be extended I would expose smart sockets as a **_switch_**. This would toggle on and off. On would be the default timer period. Also create a service **_geniushub.set_switch_override_** to allow the override duration to be changed.

Let me know your views.

**Comment by zxdavb** [comment]
@GeoffAtHome The best place to ask questions like this may be at: https://community.home-assistant.io/ - others there may be able to help you. Ping me there if you have no joy.

It is so long since I've looked at this code, and - you would not believe it - my HA server crashed a few days ago...

But, IIRC: you cannot turn **switches** on/off (only **zones**) - this is a limitation of this client, _but_: I am not aware if there is a RESTful API for this feature - are you aware of one?

**Comment by GeoffAtHome** [comment]
@zxdavb. OK - I'll post questions where you suggest.

It is a long time since I've looked at this code and any python. I have mostly being focused on TypeScript. Why did you HA server crash? I haven't had one of these for ages and this was normally associated with an upgrade. Having the HA server virtualized makes recovery easy and it is much faster than a Pi.

A switch has to be added to a zone - part of the limitation of GH. I have no problem turning a switch on and off with a RESTful API so I don't see this as an issue. In the original code I produced this was possible as was reporting switches as switches to HA. The issue I had is I did not expose an override so I only meant on for the default 1 hour.

Happy to close this for now and wait produce a PR.

**Comment by zxdavb** [comment]
It crashed during an upgrade - upgraded many times without issue before that. I agree, but this is a remote site (I do run VMs at home).

Just send me the API - it may be a quick fix.

**Comment by GeoffAtHome** [comment]
The API is similar to other zones.
To switch on the payload is and the call is made with a PATCH:
`{iMode: 16, fBoostSP: 1, iBoostTimeRemaining: 3600}`

To switch off the payload is and the call is made with a PATCH:
`{iMode: 1}`

Let me know if you need any more info. It would be great if this is a simple quick fix.

**Comment by zxdavb** [comment]
Geoff - can you send me the link to the API - I am looking at:
 - https://my.geniushub.co.uk/#tag/devices (there is no PATCH there), and:
 - https://my.geniushub.co.uk/#tag/zone/paths/~1zone~1{zoneID}/patch (only for zones)

If you're talking about on/of zones (as opposed to switches), then this should already work.

**Comment by GeoffAtHome** [comment]
The information I provided was from the developer tools in Chrome by capturing what the HA app does when a switch is turned on or off. 

Request URL: https://hub-server-2.heatgenius.co.uk/v3/zone/26
Request Method: PATCH
Status Code: 200 OK

So this is using [https://my.geniushub.co.uk/#tag/zone/paths/~1zone~1{zoneID}/patch (only for zones)](https://my.geniushub.co.uk/#tag/zone/paths/~1zone~1{zoneID}/patch (only for zones))

I am taking about a switch, a smart plug, that is in a zone. It is the only device in the zone. Happy to turn the zone on or the switch on - whatever works would suit me.

In HA the smart plug identified itself as both a switch and a binary_sensor. I cannot see it as a zone but this may be user error on my part.

When I try and call the service, geniushub.set_zone_override,  in HA  (Developer Tools, Services tab). I get the error required key not provided @ data[temperature]. Providing the key is not supported by the binary sensor.

A smart plug should support 'duration' but 'temperature' is not required. The currently implementation appears to make temperature mandatory - or it could be user error by me.

![image](https://user-images.githubusercontent.com/7040344/105711108-fb49d480-5f0f-11eb-9f90-504bb198ff82.png)

**Comment by zxdavb** [comment]
Oh, I see. To be clear:
 - the Genius **On/Off Zone** becomes a **HA Switch** (and not a HA Climate) entity
 - the Genius **Switch Device** becomes a **HA BinarySensor**

Why can't you just turn the **HA Switch** on/off via the standard service call, something like: `switch.turn_on` (instead of `genius.set_zone_overrride`)?

**Comment by GeoffAtHome** [comment]
_the Genius **On/Off Zone** becomes a **HA Switch** (and not a HA Climate) entity
the Genius **Switch Device** becomes a **HA BinarySensor**_
Correct

`switch.turn_on` and `switch.turn_off` work, but I cannot change the duration from the default of an hour. I could take a different approach and retrigger the `switch.turn_on` to extended beyond and hour or use `switch.turn_off` for less than an hour. 

Not ideal but will suffice for now.

**Comment by GeoffAtHome** [comment]
I'll see if I can extend the code to work how I believe it should and create a PR. I don't think it is too far from where it needs to be.

Hopefully this will be a non-breaking change.

**Comment by zxdavb** [comment]
Try this: in **__init__.py**, change this:
```python
SET_ZONE_MODE_SCHEMA = vol.Schema(
    {
        vol.Required(ATTR_ENTITY_ID): cv.entity_id,
        vol.Required(ATTR_ZONE_MODE): vol.In(["off", "timer", "footprint"]),
    }
)
```
... to this:
```python
SET_ZONE_MODE_SCHEMA = vol.Schema(
    {
        vol.Required(ATTR_ENTITY_ID): cv.entity_id,
        vol.Required(ATTR_ZONE_MODE): vol.In(["off", "timer", "footprint"]),
        vol.Optional(ATTR_DURATION): vol.All(
            cv.time_period,
            vol.Range(min=timedelta(minutes=5), max=timedelta(days=1)),
        ),
    }
)
```

**Comment by GeoffAtHome** [comment]
Thanks. I will check it out later today and report back. In the middle of child mining duties.

**Comment by zxdavb** [comment]
Actually, you're going to have to have a change made to the library.

**Comment by GeoffAtHome** [comment]
I have got as far as setting up the development environment and putting in a few break points. What is eluding me is what is the best way forward... what makes sense.

A HA switch does not have a timer.
A HA binary_sensor is a readonly device and cannot be switched on or off.

The duration passed over to the binary_sensor but not the switch. How can a switch retrieve the duration from the binary_sensor? 

This is probably not the right thing to do.... I have been away from this code for so long I can't remember the relationship between a GH Zone and GH device. A Zone can contains one or move device.

The what I would really like to do is to pass the duration to the switch when I call the service switch.turn_on.
Stepping back from there what is the best way forward.... something for tomorrow. Sorry for ramblings on....

**Comment by GeoffAtHome** [comment]
I have this up and running. No changes required to library only to HA side.
Testing now but hope to post a PR later today.

**Comment by GeoffAtHome** [comment]
PR created.
