### ISSUE TITLE
Home Assistant Integration failing suddenly

### ISSUE THREAD

**Issue by m90att** [manzanotti/geniushub-client#74]
The integration between Home Assistant and Genius Hub suddenly stopped working last week. I have done nothing to the integration in Home Assistant and I have done nothing to my Genius Hub system. I have rebooted my GH system three times and restarted HA countless times. Genius Hub is showing no issues or errors.

I have removed the configuration from configuration.yaml and rebooted, replaced it and rebooted again and still I see the following error:

```
Logger: homeassistant.setup
Source: components/geniushub/__init__.py:124
First occurred: 10:26:05 (1 occurrences)
Last logged: 10:26:05

Error during setup of component geniushub
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 253, in _async_setup_component
    result = await task
  File "/usr/src/homeassistant/homeassistant/components/geniushub/__init__.py", line 124, in async_setup
    await client.update()
  File "/usr/local/lib/python3.10/site-packages/geniushubclient/__init__.py", line 336, in update
    await self._update()  # now convert all the raw JSON
  File "/usr/local/lib/python3.10/site-packages/geniushubclient/__init__.py", line 303, in _update
    self.issues = [convert_issue(raw_json) for raw_json in self._issues]
  File "/usr/local/lib/python3.10/site-packages/geniushubclient/__init__.py", line 303, in <listcomp>
    self.issues = [convert_issue(raw_json) for raw_json in self._issues]
  File "/usr/local/lib/python3.10/site-packages/geniushubclient/__init__.py", line 262, in convert_issue
    device_type = self.device_by_id[raw_json["data"]["nodeID"]].data["type"]
KeyError: '29'
```

I have tried:

- removed the integration (then reboot)
- deleted all genius hub entities (reboot)
- searched files in .storage to find any mentions of 29 - there aren’t any
- searched in customisations, sensors, automations, known devices files for ‘29’ - again nothing found
- (reboot)
- added the integration (reboot)

Error is still seen. I repeated the above twice.

What version of Home Assistant Core has the issue?
2023.1.6

What type of installation are you running?
Home Assistant OS

Integration causing the issue
Genius Hub

Link to integration documentation on our website
https://www.home-assistant.io/integrations/geniushub/

Also raised here, with no responses to date
https://github.com/home-assistant/core/issues/86277

**Comment by benwainwright** [comment]
Hi!

I have the same issue, so I've spent a bit of time this evening playing with library to try to work out what is going on. It seems like the problem here is caused because the 'type' field referred to in the stack trace is populated via a hardcoded mapping - the API returns something called a `nodeHash` which I'm assuming is some kind of unique hardware identifier, and the library then maps it to readable strings like "Room Sensor" and so forth.

After a bit of debugging, I've realised that the crash is caused (at least for me) because the API is returning a `nodeHash` value not included in the map object in `const.py` - `0x0000005900030010`.

This should be a relatively easy fix, so at some point in the next week or so I'll probably fork the repo and raise a PR. OP - I can't guarantee my fix will also solve your problem without seeing what the API is returning for you.

As a note to the developer, it would probably be useful to handle the case where genius introduce new devices that you don't recognise and either
- Throw a useful error message that at least tells people why its broken or
- Perhaps populate strings like 'type' with something like 'Unknown Device'

**Comment by m90att** [comment]
My Genius Hub Home Assistant integration is still failing, is there a resolution path for this issue yet please?  Winter is approaching!  Latest example of failure from logs:

```
Logger: homeassistant.setup
Source: setup.py:288
First occurred: 15:07:31 (1 occurrences)
Last logged: 15:07:31

Error during setup of component geniushub
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 288, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/geniushub/__init__.py", line 124, in async_setup
    await client.update()
  File "/usr/local/lib/python3.11/site-packages/geniushubclient/__init__.py", line 260, in update
    super().update()  # now parse all the JSON
    ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/geniushubclient/__init__.py", line 201, in update
    self.issues = [convert_issue(raw_json) for raw_json in self._issues]
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/geniushubclient/__init__.py", line 201, in <listcomp>
    self.issues = [convert_issue(raw_json) for raw_json in self._issues]
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/geniushubclient/__init__.py", line 161, in convert_issue
    device_type = self.device_by_id[raw_json["data"]["nodeID"]].data["type"]
                  ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: '8'

```

**Comment by GeoffAtHome** [comment]
@m90att please retest this with the latest version of the geniushubclient and post the results here.

**Comment by m90att** [comment]
Hi @GeoffAtHome, I no longer use GH as, after 8 years of faults and bugs, I decided enough was enough.  I'm sorry I can't verify it for you.  Thanks for all your hard work on it and good luck for the future.

**Comment by GeoffAtHome** [comment]
@m90att I know how you feel. GH is not really the product I signed up for. With what I have learnt I would have done the whole lot in HA. After all, it is just a switch for the boiler and a collection sensors and TRVs. Today there are many better sensors that don't eat batteries.

Out of interest, what system do you switch too?

**Comment by m90att** [comment]
Hi, I went with Tado.  So far it's been perfect and the existing integration with HA means I can control it from there.
________________________________

**Comment by manzanotti** [comment]
Yeah, I must admit to being pretty disillusioned with GH the last few years. The amount of batteries the sensors go through is infuriating.

I am trying to get a heat pump installed, haven't decided what I'll do if that goes in, as I don't know if you really need that level of room-by-room control, or whether having the system run for more of the day is the best way.
